create table if not exists public.schedule_overrides (
  id bigint generated by default as identity primary key,
  day_key text not null,
  is_active boolean not null default true,
  is_closed boolean not null default false,
  message text,
  gym_hours text,
  classes_json jsonb,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.schedule_date_overrides (
  id bigint generated by default as identity primary key,
  date_iso text not null,
  is_active boolean not null default true,
  is_closed boolean not null default false,
  message text,
  gym_hours text,
  classes_json jsonb,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.member_billing_history (
  id bigint generated by default as identity primary key,
  user_email text not null,
  billed_at timestamp with time zone not null default now(),
  amount numeric(10,2) not null,
  status text not null default 'paid',
  method text,
  note text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.member_attendance_history (
  id bigint generated by default as identity primary key,
  user_email text not null,
  attended_at timestamp with time zone not null default now(),
  title text not null,
  coach text,
  note text,
  created_at timestamp with time zone not null default now()
);

insert into public.schedule_date_overrides (date_iso, is_closed, message)
values ('2026-05-25', true, 'Memorial Day - no classes')
on conflict do nothing;
