create table if not exists public.schedule_overrides (
  id bigint generated by default as identity primary key,
  day_key text not null,
  is_active boolean not null default true,
  is_closed boolean not null default false,
  message text,
  gym_hours text,
  classes_json jsonb,
  created_at timestamp with time zone not null default now()
);

create unique index if not exists schedule_overrides_day_key_unique
  on public.schedule_overrides (day_key)
  where is_active = true;

create table if not exists public.schedule_date_overrides (
  id bigint generated by default as identity primary key,
  date_iso text not null,
  is_active boolean not null default true,
  is_closed boolean not null default false,
  message text,
  gym_hours text,
  classes_json jsonb,
  created_by text,
  created_at timestamp with time zone not null default now()
);

alter table public.schedule_date_overrides add column if not exists created_by text;

create unique index if not exists schedule_date_overrides_date_unique
  on public.schedule_date_overrides (date_iso)
  where is_active = true;

create table if not exists public.member_billing_history (
  id bigint generated by default as identity primary key,
  user_email text not null,
  billed_at timestamp with time zone not null default now(),
  amount numeric(10,2) not null,
  status text not null default 'paid',
  method text,
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists member_billing_history_user_email_idx
  on public.member_billing_history (lower(user_email), billed_at desc);

create table if not exists public.member_attendance_history (
  id bigint generated by default as identity primary key,
  user_email text not null,
  attended_at timestamp with time zone not null default now(),
  title text not null,
  coach text,
  note text,
  created_at timestamp with time zone not null default now()
);

create index if not exists member_attendance_history_user_email_idx
  on public.member_attendance_history (lower(user_email), attended_at desc);

create table if not exists public.employee_timesheets (
  id bigint generated by default as identity primary key,
  employee_email text not null,
  class_date date not null,
  class_type text not null,
  duration_hours numeric(6,2) not null,
  students_count integer,
  notes text,
  created_at timestamp with time zone not null default now()
);

create index if not exists employee_timesheets_employee_email_idx
  on public.employee_timesheets (lower(employee_email), class_date desc);

alter table public.schedule_overrides enable row level security;
alter table public.schedule_date_overrides enable row level security;
alter table public.member_billing_history enable row level security;
alter table public.member_attendance_history enable row level security;
alter table public.employee_timesheets enable row level security;

drop policy if exists "public read active schedule_overrides" on public.schedule_overrides;
create policy "public read active schedule_overrides"
  on public.schedule_overrides
  for select
  using (is_active = true);

drop policy if exists "public read active schedule_date_overrides" on public.schedule_date_overrides;
create policy "public read active schedule_date_overrides"
  on public.schedule_date_overrides
  for select
  using (is_active = true);

drop policy if exists "member read own billing history" on public.member_billing_history;
create policy "member read own billing history"
  on public.member_billing_history
  for select
  using (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "member read own attendance history" on public.member_attendance_history;
create policy "member read own attendance history"
  on public.member_attendance_history
  for select
  using (lower(user_email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists "admin manage schedule_date_overrides" on public.schedule_date_overrides;
create policy "admin manage schedule_date_overrides"
  on public.schedule_date_overrides
  for all
  using (lower(coalesce(auth.jwt() ->> 'email', '')) in ('info@cpamma.com', 'ryangruhn@gmail.com', 'frontdesk@cpamma.com'))
  with check (lower(coalesce(auth.jwt() ->> 'email', '')) in ('info@cpamma.com', 'ryangruhn@gmail.com', 'frontdesk@cpamma.com'));

drop policy if exists "employee insert own timesheets" on public.employee_timesheets;
create policy "employee insert own timesheets"
  on public.employee_timesheets
  for insert
  with check (
    lower(employee_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    and lower(coalesce(auth.jwt() ->> 'email', '')) in ('info@cpamma.com', 'ryangruhn@gmail.com', 'frontdesk@cpamma.com')
  );

drop policy if exists "employee read own timesheets" on public.employee_timesheets;
create policy "employee read own timesheets"
  on public.employee_timesheets
  for select
  using (
    lower(employee_email) = lower(coalesce(auth.jwt() ->> 'email', ''))
    or lower(coalesce(auth.jwt() ->> 'email', '')) in ('info@cpamma.com', 'ryangruhn@gmail.com', 'frontdesk@cpamma.com')
  );

insert into public.schedule_date_overrides (date_iso, is_closed, message, created_by)
values ('2026-05-25', true, 'Memorial Day - no classes', 'info@cpamma.com')
on conflict do nothing;
